Checknode should be ready for prime-time
* remove check for gather arg, use TESTINFO from tmcc hwinfo
  instead. Only call tmcc once. Let non-MFS boot collect data.
* tmcc hwinfo not return a TESTINFO line. Handle the LOGDIR, COLLECT
  and CHECK indicators
* Do to variable scoping make sure everything runs in the shell.
  Do not 'exit' from called programs. Source called programs instead
  of starting new shells.
* Nothing wrong with the which() function I put in since the
  MFS/busybox installation does not have one, but if we have a real
  which(1) program use it.
* output format changes and programming space changes
* remove check for gather arg, use TESTINFO from tmcc hwinfo
  instead. Only call tmcc once. Let non-MFS boot collect data.
* tmcc hwinfo not returning a TESTINFO line. Handle the LOGDIR, COLLECT
  and CHECK indicators
* Do to variable scoping make sure everything runs in the shell.
* Do not 'exit' from called programs. Source called programs instead of
  starting new shells.
* Nothing wrong with the which() function I put in since the MFS/busybox
  installation does not have one, but if we have a real which(1) program
  use it.
* call sub-programs by sourcing not by starting new shell.
* oops mfsmode is not set until initialize is run. also set -e -u to
  catch this type of thing.

Checknode tests once again run in standard images and can collect
data.

* All tests can now be "sourced" from gatherinv to insure everything
  runs in a single shell.
* All tests can also be called standalone.
* MFS mode and non-MFS mode honor the CHECK and COLLECT flags.
* Create, if necessary, a new project save directory.
* This will be needed once every-time checknodes is run in a new project.
  path is /proj/{pid}/nodecheck.
* If script can't run quit with a 'return 0' so the rest of the checks
  can continue.

Change filename gatherinv -> checknode

* Can't run in MFS mode if not in the emulab-ops pid

diff --git a/clientside/tmcc/common/checknode/diskcheck b/clientside/tmcc/common/checknode/diskcheck
--- a/clientside/tmcc/common/checknode/diskcheck
+++ b/clientside/tmcc/common/checknode/diskcheck
@@ -35,18 +35,21 @@ declare err=""
 source checkutils.sh
 source hbis.sh
 
+x=$(caller)
+[[ "${x/NULL}" = "$x" ]] && declare -ri diskcheck_standalone=0 || declare -ri diskcheck_standalone=1
+
 ## declare -p todo_exit
 
-main() {
-    inithostname
-    initlogs $@
+main_diskcheck() {
+    initialize $@
+    cp /dev/null $tmplog
 
     SMARTCTL=$(findSmartctl)
     drivenames=$(getdrivenames)
 
     if [ -z "$drivenames" ] ; then
 	echo "No drives found. exit"
-	exit 1
+	(( $diskcheck_standalone )) && exit 1 || return 1
     fi
 
     # array to put drive inventory
@@ -175,7 +178,7 @@ main() {
 	driveinv[$idx]=${d[@]}
     done
 
-    if [ -f ${logfile4tb} ] ; then
+    if (( $collect_flag )) ; then
 	printf "%s%d\n"  "DISKINFO UNITS=" ${numberofdrives} >> ${logfile4tb}
 	for (( idx=0; idx<$numberofdrives; idx++)) ; do
 	    unset -v d ; declare -a d=(${driveinv[$idx]})
@@ -197,10 +200,13 @@ main() {
     fi
 
 # we are done if in MFS mode
-(( $mfsmode )) && exit 0
+if (( $mfsmode )) ; then
+    (( $diskcheck_standalone )) && exit 0 || return 0
+fi
 
 #output to log file
 {
+echo "Diskcheck $(date): "
 echo -e "name\t\tdriver\ttype\tsize\ttemp\tmodel\t\t\tserial"
 for ((idx=0; idx<${numberofdrives}; idx++)) ; do
     unset -v d ; declare -a d=(${driveinv[$idx]})
@@ -210,83 +216,80 @@ done
 cat ${tmplog} >> ${logfile} 
 
 driveinfo=""
-
 # echo name,size and serial to stdout, addr serialnumber
 for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
     unset -v d ; declare -a d=(${driveinv[$idx]})
     echo -n "${d[$name_val]} ${d[$size_val]} ${d[$serial_val]}  "
-    driveinfo+="${d[$serial]} "
+    driveinfo+="${d[$serial_val]} "
 done
-
-echo "" ; exit
-
+echo ""
 
 driveinfo=${driveinfo% } # get rid of trailing space
 
+if (( $check_flag )) ; then
 # Now check against the testbed DB
-
-tbinfo=$(getfromtb diskinfo $host)
-echo tbinfo:|"$tbinfo"|
-exit
-error=$?
-# echo drivesize:$drivesize: tbinfo:$tbinfo: error:$error
-
-
-{ 
+# readtmcinfo /proj/emulab-ops/nodecheck/pc507/pc507  tmccinfo
+    tbinfo=$(getfromtb DISKUNIT)
+    tbinfo=${tbinfo% }  # get rid of trailing space
+    
+# echo driveinfo:$driveinfo: tbinfo:$tbinfo: 
+    
+{
 #save for both output to stdout and log file 
-if [ -z "$tbinfo" ] ; then
-    failed="TBmiss no info"
-    echo "TBmiss empty info returned. Have ${tbinfo[@]} FAILED"
-fi
-
-#lower case
-tbinfo=${tbinfo,,}
-driveinfo=${driveinfo,,}
+    if [ -z "$tbinfo" ] ; then
+	failed="TBmiss no info"
+	echo "TBmiss empty info returned. "
+    fi
+    
+#upper case
+    tbinfo=${tbinfo^^}
+    driveinfo=${driveinfo^^}
 # turn space seperated string into array
-unset -v tb; declare -a tb=(${tbinfo// / })
-unset -v have; declare -a have=(${driveinfo// / })
-
-havecnt=${#have[*]}
-tbcnt=${#tb[*]}
-numserial=${tbcnt}
-maxcnt=${tbcnt}
-
-if [[ ${tbcnt} -ne ${havecnt} ]] ; then
-    failed="TBmiss"
+    unset -v tb; declare -a tb=(${tbinfo// / })
+    unset -v have; declare -a have=(${driveinfo// / })
+    
+    havecnt=${#have[*]}
+    tbcnt=${#tb[*]}
+    numserial=${tbcnt}
+    maxcnt=${tbcnt}
+    
+    if [[ ${tbcnt} -ne ${havecnt} ]] ; then
+	failed="TBmiss"
     [[ ${tbcnt} -gt ${havecnt} ]] && maxcnt=${tbcnt} || maxcnt=${havecnt}
-fi
-
-for ((idx=0; idx<$maxcnt; idx++)) ; do
-    for ((ifi=0; ifi<$havecnt; ifi++)) ; do
-	for ((tbi=0; tbi<$tbcnt; tbi++)) ; do
-	    if [ "${have[$ifi]}" = "${tb[$tbi]}" ] ; then
-		have[$ifi]=''
-		tb[$tbi]=''
+    fi
+    
+    for ((idx=0; idx<$maxcnt; idx++)) ; do
+	for ((ifi=0; ifi<$havecnt; ifi++)) ; do
+	    for ((tbi=0; tbi<$tbcnt; tbi++)) ; do
+		if [ "${have[$ifi]}" = "${tb[$tbi]}" ] ; then
+		    have[$ifi]=''
+		    tb[$tbi]=''
 	    fi
+	    done
 	done
     done
-done
 #turn array into string
-haveresult=${have[@]}
-tbresult=${tb[@]}
-
-if [[ "$haveresult" || "$tbresult" ]] ; then
-    if [[ $haveresult ]] ; then
+    haveresult=${have[@]-""}
+    tbresult=${tb[@]-""}
+    
+    if [[ "$haveresult" || "$tbresult" ]] ; then
+	if [[ $haveresult ]] ; then
 	failed="${failed}: NotIn TB $haveresult"
-    fi
-    if [[ $tbresult ]] ; then
-	failed="${failed}: TB Claims $tbresult"
-    fi
+	fi
+	if [[ $tbresult ]] ; then
+	    failed="${failed}: TB Claims $tbresult"
+	fi
 fi
-
-echo -n "Have $havecnt drive"
-[[ ${havecnt} -gt 1 ]] && echo -n "s" 
-[[ -z ${failed} ]] && echo " OK" || echo " $failed" FAILED
-
+    
+    echo -n "Have $havecnt drive"
+    [[ ${havecnt} -gt 1 ]] && echo -n "s" 
+    [[ -z ${failed} ]] && echo " OK" || echo " $failed" FAILED
+    
 
 } > ${tmplog} 2>&1
-cat ${tmplog} >> $logfile
-cat ${tmplog}
+    cat ${tmplog} >> $logfile
+    cat ${tmplog}
+fi # check_flag
 
 }
 
@@ -351,7 +354,7 @@ case $err in
 		;;
 	    * )
 		echo "${FUNCNAME[0]}:${LINENO} Internal error"
-		exit
+		(( $diskcheck_standalone )) && exit 1 || return 1
 		;;
 	esac
 	unset -v scan
@@ -542,7 +545,7 @@ getbpers() {
 	    [[ $res ]] || res=512
 	    ;;
 	* ) echo "$FUNCNAME internal error"
-	    exit 1
+	(( $diskcheck_standalone )) && exit 1 || return 1
 	    ;;
     esac
     echo $res
@@ -597,7 +600,7 @@ getsectors() {
 	    [[ $res ]] || res=0
 	    ;;
 	* ) echo "$FUNCNAME internal error"
-	    exit 1
+	(( $diskcheck_standalone )) && exit 1 || return 1
 	    ;;
     esac
     echo $res
@@ -632,12 +635,9 @@ getwspeed() {
 	args="$args count=8000"
     fi
     add_on_exit 'rm -f /tmp/ddresultw'
-    mynn=${#todo_exit[*]}
-    todo_exit[$mynn]='those are mine'
     $dd if=/dev/zero of=$hdname $args >/tmp/ddresultw 2>&1
     res=$(grep bytes /tmp/ddresultw)
     echo $(parsedd $res)
-    rm -f /tmp/ddresultw
     return 0
 }
 getrspeed() { 
@@ -666,7 +666,6 @@ getrspeed() {
     $dd of=/dev/null if=$hdname $args >/tmp/ddresultr 2>&1
     res=$(grep bytes /tmp/ddresultr)
     echo $(parsedd $res)
-    rm -f /tmp/ddresultr
     return 0
 }
 
@@ -700,7 +699,6 @@ parsedd() {
     return 0
 }
 
-main $@
-#cleanup
+main_diskcheck $@
 
-exit 0
+(( $diskcheck_standalone )) && exit 0 || return 0
diff --git a/clientside/tmcc/common/checknode/memcheck b/clientside/tmcc/common/checknode/memcheck
--- a/clientside/tmcc/common/checknode/memcheck
+++ b/clientside/tmcc/common/checknode/memcheck
@@ -28,30 +28,26 @@ _256KMiB=262144
 _1KGiB=1048576
 _32KGiB=33554432
 
-echo -n ' Starting memcheck..'
+echo -n ' Starting Memcheck..'
 
 source checkutils.sh
 source hbis.sh
 
+x=$(caller)
+[[ "${x/NULL}" = "$x" ]] && declare -ri memcheck_standalone=0 || declare -ri memcheck_standalone=1
+
 declare failed="" s=""
 
-inithostname
-initlogs $@
+initialize $@
+cp /dev/null $tmplog
 
-#set +x
-#exit on unbound var
-set -u
-#exit on any error
-set -e
-
-# only called on error, should just get rig of
 finish() {
-    echo "memcheck `date`" >> ${logfile}
+    echo -n "Memcheck `date`: " >> ${logfile}
     cat ${tmplog} >> ${logfile} 
     
     echo "$failed"
     echo "$failed" >> ${logfile} 
-    exit 1
+    (( $memcheck_standalone )) && exit 0 || return 0
 }
 
 s=""
@@ -59,7 +55,7 @@ s=""
 # check that external need program are installed
 case $os in
     Linux )
-	if [ -f ${logfile4tb} ] ; then
+	if (( $mfsmode )) ; then
 	    progs="cat grep"
 	else
 	    progs="cat grep bc"
@@ -71,7 +67,7 @@ case $os in
     * )
 	failed="Unknown OS :$os:"
 	finish
-	exit 1
+	(( $memcheck_standalone )) && exit 1 || return 1
 	;;
 esac
 for i in $progs ; do
@@ -89,7 +85,7 @@ case $os in
     Linux )
 	    unset -v d ; declare -a d=($(cat /proc/meminfo | grep MemTotal))
 	    # we don't have the use of bc in mfs/load boot
-	    if [ -f ${logfile4tb} ] ; then
+	    if (( $collect_flag )) ; then
 		# punt punt punt
 		number=${d[1]}
 		if (( number > $_32KGiB )) ; then
@@ -116,7 +112,7 @@ case $os in
 		    number=$(echo "scale=0; (${d[1]} * 1.0) / 1;" | bc)
 		fi
 	    fi
-		
+	    
 	    mi=${number}${d[2]}
 	    meminfo=$(hbis $mi)
 	    ;;
@@ -140,28 +136,28 @@ esac
 echo -n "Found phys memory $meminfo"
 } >> ${tmplog} 2>&1
 
-# if saving data for testbed database
 num=${meminfo//[a-z]*/}
 num=${meminfo//[A-Z]*/}
 base=${meminfo//[0-9]/}
-#it is MiB or GiB
-if [ "$base" == "GiB" ] ; then
+    #it is MiB or GiB
+if [ "$base" = "GiB" ] ; then
     num=$(($num * 1024))
 fi
-if [ -f ${logfile4tb} ] ; then
+
+# if saving data for testbed database
+if (( $collect_flag )) ; then
     printf "MEMINFO SIZE=%s\n" ${num} >> ${logfile4tb}
-    exit 0
 fi
 
-# done at this point in MFS
 # we are done if in MFS mode
-(( $mfsmode )) && exit 0
+if (( $mfsmode )) ; then
+    (( $memcheck_standalone )) && exit 0 || return 0
+fi
 
-
-tbinfo=$(getfromtb meminfo $host)
+tbinfo=$(getfromtb MEMINFO)
 
 {
-if [ "$meminfo" == "$tbinfo" ] ; then
+if [ "$num" = "$tbinfo" ] ; then
     echo " Equals node inventory $tbinfo"
 else
     echo " Does not equals node inventory $tbinfo"    
@@ -169,9 +165,9 @@ else
 fi
 } >> ${tmplog} 2>&1
 
-echo "memcheck `date`" >> ${logfile}
+echo -n "Memcheck `date`: " >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo "$tbinfo OK" || echo "TBmiss Have |$meminfo| Want |$tbinfo| FAILED"
+[[ -z ${failed} ]] && echo "$meminfo" || echo "TBmiss Have |$meminfo| Want |$tbinfo| FAILED"
 
-exit 0
+(( $memcheck_standalone )) && exit 0 || return 0
diff --git a/clientside/tmcc/common/checknode/timecheck b/clientside/tmcc/common/checknode/timecheck
--- a/clientside/tmcc/common/checknode/timecheck
+++ b/clientside/tmcc/common/checknode/timecheck
@@ -27,36 +27,25 @@ echo -n ' Starting timecheck.. '
 ntpserver="ntp1"
 maxdrift="0.001"
 
-#ntpserver="time.xmission.com"
+source checkutils.sh
 
-os=`uname`
-host=`hostname`
-failed=""
-if [ -e "/var/emulab/boot/realname" ]; then
-    host=`cat /var/emulab/boot/realname`
-fi
+initialize $@
 
-
-# setup logging
-if [ $1 ] ; then
-    logfile=$1
-else
-    logfile="/tmp/nodecheck.log"
-fi
-tmplog=/tmp/.$$.log
-cat /dev/null > ${tmplog}
+# are we called from somewhere or are we standalone
+x=$(caller)
+[[ "${x/NULL}" = "$x" ]] && declare -ri timecheck_standalone=0 || declare -ri timecheck_standalone=1
 
 # check that external need program are installed
 s=""
 case $os in
     Linux | FreeBSD )
-	progs="tr bc ntpdate"
+	progs="tr bc ntpdate host"
 	;;
     * )
 	failed="Unknown OS :$os: FAILED"
 	echo "$failed" >> ${logfile}
 	echo "$failed"
-	exit 1
+	(( $timecheck_standalone )) && exit 0 || return 0
 	;;
 esac
 for i in $progs ; do
@@ -66,14 +55,34 @@ if [ -n "$s" ] ; then
     failed=" Unable to run need missing command(s) $s FAILED"
     echo "$failed" >> ${logfile}
     echo "$failed"
-    exit 1
+    (( $timecheck_standalone )) && exit 0 || return 0
 fi
-
-#exit on unbound var
-set -u
 
 {
 unset -v d ; declare -a d=()
+
+dnsok=$(host $ntpserver) 2>/dev/null
+if [ "${dnsok/NXDOMAIN}" != "$dnsok" ] ; then
+    echo -n "WARNING ntpserver $ntpserver unknown. " >> ${logfile}
+    x=$(/usr/local/etc/emulab/tmcc ntpinfo)
+    if [ -n "$x" ] ; then
+	ntpserver=${x/SERVER=}
+    else
+	echo -n "tmcc ntpinfo also failed. Last try from resolv.conf" >> ${logfile}
+	x=$(grep search /etc/resolv.conf)
+	if [ -n "$x" ] ; then
+	    ntpserver="${ntpserver}.${x/search }"
+	fi
+    fi
+    echo -n "Trying ntpserver $ntpserver " >> ${logfile}
+    dnsok=$(host $ntpserver) 2>/dev/null
+    if [ "${dnsok/NXDOMAIN}" != "$dnsok" ] ; then
+	echo "WARNING $ntpserver also unknown. " >> ${logfile}
+	echo "Giving up">> ${logfile}
+	(( $timecheck_standalone )) && exit 0 || return 0
+    fi
+fi
+
 case $os in
     Linux | FreeBSD )
 	d=($(ntpdate -q $ntpserver))
@@ -89,7 +98,7 @@ case $os in
 	[[ $a > $maxdrift ]] && failed="maxdrift"
 	if  [ -z "${failed}" ]; then
 	    echo "Time check passed offset $offset allowed $maxdrift"
-	elif [ "${failed}" == "maxdrift" ] ; then
+	elif [ "${failed}" = "maxdrift" ] ; then
 	    echo "Time check failed offset $offset greater then $maxdrift second "
 	else
 	    echo "${failed}"
@@ -103,7 +112,7 @@ case $os in
 esac
 } >> ${tmplog} 2>&1
 
-echo "timecheck `date`" >> ${logfile}
+echo -n "Timecheck `date`: " >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
 if [ -z "${failed}" ] ; then 
@@ -114,4 +123,7 @@ else
     echo "${failed} FAILED"
 fi
 
-exit 0
+# Check to if called standalone or source from another shell
+(( $timecheck_standalone )) && exit 0 || return 0
+
+# return 0
