Get the assorted versions of slicefix in sync.
All now include the localization code that Leigh added.

diff --git a/clientside/tmcc/freebsd/slicefix b/clientside/tmcc/freebsd/slicefix
--- a/clientside/tmcc/freebsd/slicefix
+++ b/clientside/tmcc/freebsd/slicefix
@@ -13,6 +13,16 @@ else
 	ETCDIR=/etc/emulab
 fi
 
+# XXX should fix paths.sh but I am afraid of the consequences
+if [ -d "/etc/emulab" -a "$ETCDIR" = "/etc/testbed" ]; then
+	ETCDIR=/etc/emulab
+	for f in isvgaonly isflash bossnode emulab.pem client.pem; do
+		if [ -e "/etc/testbed/$f" -a ! -e "/etc/emulab/$f" ]; then
+			mv /etc/testbed/$f /etc/emulab/$f
+		fi
+	done
+fi    
+
 disk="ad0"
 
 case $# in
@@ -162,6 +172,7 @@ dofreebsd() {
 	echo "fixing FreeBSD root partition ${disk}s${part}a"
 	fsck -p $rootdev || {
 		# 8.x fsck fails to determine the FS type, try again with ufs
+		echo "retrying fsck with '-t ufs'"
 		fsck -t ufs -p $rootdev || {
 		    echo "Fsck of $rootdev failed"
 		    return 1
@@ -306,11 +317,14 @@ dofreebsd() {
 	    fi
 	fi
 
+	#
+	# Localize the image. We only do this if the MFS we are running in
+	# has the necessary files.
+	#
 	if islocalized; then
 	    # Check the certs.
 	    if [ -e $ETCDIR/emulab.pem ]; then
 		cmp -s $ETCDIR/emulab.pem /mnt/etc/emulab/emulab.pem
-
 		if [ $? -ne 0 ]; then
 		    changecerts=1
 		    fixit=1
@@ -318,14 +332,13 @@ dofreebsd() {
 	    fi
 	    if [ -e $ETCDIR/client.pem ]; then
 		cmp -s $ETCDIR/client.pem /mnt/etc/emulab/client.pem
-
 		if [ $? -ne 0 ]; then
 		    changecerts=1
 		    fixit=1
 		fi
 	    fi
 
-	    # Check the root keys
+	    # Check the root keys.
 	    if [ -e /root/.ssh/authorized_keys2 ]; then
 		cmp -s /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys
 		if [ $? -ne 0 ]; then
@@ -335,21 +348,21 @@ dofreebsd() {
 	    fi
 	
 	    # Check the host keys.
-	    if [ -e /etc/ssh/ssh_host_key -a -d /mnt/etc/ssh ]; then
+	    if [ -e /etc/ssh/ssh_host_key ]; then
 		cmp -s /etc/ssh/ssh_host_key /mnt/etc/ssh/ssh_host_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
 		    fixit=1
 		fi
 	    fi
-	    if [ -e /etc/ssh/ssh_host_rsa_key -a -d /mnt/etc/ssh ]; then
+	    if [ -e /etc/ssh/ssh_host_rsa_key ]; then
 		cmp -s /etc/ssh/ssh_host_rsa_key /mnt/etc/ssh/ssh_host_rsa_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
 		    fixit=1
 		fi
 	    fi
-	    if [ -e /etc/ssh/ssh_host_dsa_key -a -d /mnt/etc/ssh ]; then
+	    if [ -e /etc/ssh/ssh_host_dsa_key ]; then
 		cmp -s /etc/ssh/ssh_host_dsa_key /mnt/etc/ssh/ssh_host_dsa_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
@@ -513,7 +526,7 @@ EOF1
 		    return 1
 		}
 	    fi
-	    cp -p $ETCDIR/emulab.pem $ETCDIR/client.pem /mnt/etc/emulab || {
+	    cp -p $ETCDIR/emulab.pem $ETCDIR/client.pem /mnt/etc/emulab/ || {
 	        echo "Failed to create $ETCDIR/emulab.pem or $ETCDIR/client.pem"
 		umount $rootdev
 		return 1
@@ -522,7 +535,7 @@ EOF1
 
 	# Copy in new root keys
 	if [ $changerootkeys -eq 1 ]; then
-	    echo "  updating /root/.ssh/authorized_keys2"
+	    echo "  updating /root/.ssh/authorized_keys"
 
 	    if [ ! -d /mnt/root/.ssh ]; then
 		mkdir -m 700 /mnt/root/.ssh || {
@@ -531,7 +544,13 @@ EOF1
 		    return 1
 		}
 	    fi
-	    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh || {
+	    # copy to both authorized_keys and _keys2
+	    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys || {
+	        echo "Failed to create /root/.ssh/authorized_keys"
+		umount $rootdev
+		return 1
+	    }
+	    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/ || {
 	        echo "Failed to create /root/.ssh/authorized_keys2"
 		umount $rootdev
 		return 1
@@ -549,7 +568,7 @@ EOF1
 		    return 1
 		}
 	    fi
-	    cp -p /etc/ssh/ssh_host_* /mnt/etc/ssh || {
+	    cp -p /etc/ssh/ssh_host_* /mnt/etc/ssh/ || {
 	        echo "Failed to create /etc/ssh/hostkeys"
 		umount $rootdev
 		return 1
@@ -810,8 +829,12 @@ dolinux() {
 	    dd if=/dev/urandom of=/mnt/var/lib/random-seed bs=512 count=1 >/dev/null 2>&1
 	fi
 
-	# Check the certs.
+	#
+	# Localize the image. We only do this if the MFS we are running in
+	# has the necessary files.
+	#
 	if islocalized; then
+	    # Check the certs.
 	    if [ ! -d /mnt/etc/emulab ]; then
 		mkdir -m 755 /mnt/etc/emulab || {
 	            echo "Failed to mkdir /mnt/etc/emulab"
@@ -821,10 +844,9 @@ dolinux() {
 	    fi
 	    if [ -e $ETCDIR/emulab.pem ]; then
 		cmp -s $ETCDIR/emulab.pem /mnt/etc/emulab/emulab.pem
-
 		if [ $? -ne 0 ]; then
 		    echo "  updating /mnt/etc/emulab/emulab.pem"
-		    cp -p $ETCDIR/emulab.pem /mnt/etc/emulab || {
+		    cp -p $ETCDIR/emulab.pem /mnt/etc/emulab/ || {
 			echo "Failed to create $ETCDIR/emulab.pem"
 			umount $rootdev
 			return 1
@@ -833,10 +855,9 @@ dolinux() {
 	    fi
 	    if [ -e $ETCDIR/client.pem ]; then
 		cmp -s $ETCDIR/client.pem /mnt/etc/emulab/client.pem
-
 		if [ $? -ne 0 ]; then
 		    echo "  updating /mnt/etc/emulab/client.pem"
-		    cp -p $ETCDIR/client.pem /mnt/etc/emulab || {
+		    cp -p $ETCDIR/client.pem /mnt/etc/emulab/ || {
 			echo "Failed to create $ETCDIR/client.pem"
 			umount $rootdev
 			return 1
@@ -844,11 +865,11 @@ dolinux() {
 		fi
 	    fi
 
-	    # Check the root keys
+	    # Check the root keys.
 	    if [ -e /root/.ssh/authorized_keys2 ]; then
 		cmp -s /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys
 		if [ $? -ne 0 ]; then
-		    echo "  updating /root/.ssh/authorized_keys2"
+		    echo "  updating /root/.ssh/authorized_keys"
 		    
 		    if [ ! -d /mnt/root/.ssh ]; then
 			mkdir -m 700 /mnt/root/.ssh || {
@@ -857,7 +878,13 @@ dolinux() {
 			    return 1
 			}
 		    fi
-		    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh || {
+		    # copy to both authorized_keys and _keys2
+		    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys || {
+			echo "Failed to create /root/.ssh/authorized_keys"
+			umount $rootdev
+			return 1
+		    }
+		    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/ || {
 			echo "Failed to create /root/.ssh/authorized_keys2"
 			umount $rootdev
 			return 1
@@ -865,21 +892,21 @@ dolinux() {
 		fi
 	    fi
 
-	    changehostkeys=0
   	    # Check the host keys.
-	    if [ -e /etc/ssh/ssh_host_key -a -d /mnt/etc/ssh ]; then
+	    changehostkeys=0
+	    if [ -e /etc/ssh/ssh_host_key ]; then
 		cmp -s /etc/ssh/ssh_host_key /mnt/etc/ssh/ssh_host_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
 		fi
 	    fi
-	    if [ -e /etc/ssh/ssh_host_rsa_key -a -d /mnt/etc/ssh ]; then
+	    if [ -e /etc/ssh/ssh_host_rsa_key ]; then
 		cmp -s /etc/ssh/ssh_host_rsa_key /mnt/etc/ssh/ssh_host_rsa_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
 		fi
 	    fi
-	    if [ -e /etc/ssh/ssh_host_dsa_key -a -d /mnt/etc/ssh ]; then
+	    if [ -e /etc/ssh/ssh_host_dsa_key ]; then
 		cmp -s /etc/ssh/ssh_host_dsa_key /mnt/etc/ssh/ssh_host_dsa_key
 		if [ $? -ne 0 ]; then
 		    changehostkeys=1
@@ -895,7 +922,7 @@ dolinux() {
 			return 1
 		    }
 		fi
-		cp -p /etc/ssh/ssh_host_* /mnt/etc/ssh || {
+		cp -p /etc/ssh/ssh_host_* /mnt/etc/ssh/ || {
 	            echo "Failed to create /etc/ssh/hostkeys"
 		    umount $rootdev
 		    return 1
diff --git a/clientside/tmcc/linux/linux_slicefix b/clientside/tmcc/linux/linux_slicefix
--- a/clientside/tmcc/linux/linux_slicefix
+++ b/clientside/tmcc/linux/linux_slicefix
@@ -363,6 +363,133 @@ if [ -f $imageroot/var/lib/random-seed -a -c /dev/urandom ]; then
     dd if=/dev/urandom of=$imageroot/var/lib/random-seed bs=512 count=1 >/dev/null 2>&1
 fi
 
+# Indicates the MFS has been properly localized and we can copy stuff
+# into the image.
+LOCALIZED="/.localized"
+
+islocalized()
+{
+    if [ -e $LOCALIZED ]; then
+	return 0;
+    fi
+    return 1;
+}
+
+#
+# Localize the image. We only do this if the MFS we are running in
+# has the necessary files.
+#
+if islocalized; then
+    # Check the certs.
+    if [ ! -d $imageroot/etc/emulab ]; then
+	mkdir -m 755 $imageroot/etc/emulab || {
+            echo "Failed to mkdir $imageroot/etc/emulab"
+	    umount $rootdev
+	    return 1
+	}
+    fi
+    if [ -e $ETCDIR/emulab.pem ]; then
+	cmp -s $ETCDIR/emulab.pem $imageroot/etc/emulab/emulab.pem
+	if [ $? -ne 0 ]; then
+	    echo "  updating $imageroot/etc/emulab/emulab.pem"
+	    cp -p $ETCDIR/emulab.pem $imageroot/etc/emulab/ || {
+		echo "Failed to create $ETCDIR/emulab.pem"
+		umount $rootdev
+		return 1
+	    }
+	fi
+    fi
+    if [ -e $ETCDIR/client.pem ]; then
+	cmp -s $ETCDIR/client.pem $imageroot/etc/emulab/client.pem
+	if [ $? -ne 0 ]; then
+	    echo "  updating $imageroot/etc/emulab/client.pem"
+	    cp -p $ETCDIR/client.pem $imageroot/etc/emulab/ || {
+		echo "Failed to create $ETCDIR/client.pem"
+		umount $rootdev
+		return 1
+	    }
+	fi
+    fi
+
+    # Check the root keys
+    if [ -e /root/.ssh/authorized_keys2 ]; then
+	cmp -s /root/.ssh/authorized_keys2 $imageroot/root/.ssh/authorized_keys
+	if [ $? -ne 0 ]; then
+	    echo "  updating /root/.ssh/authorized_keys"
+	    
+	    if [ ! -d $imageroot/root/.ssh ]; then
+		mkdir -m 700 $imageroot/root/.ssh || {
+		    echo "Failed to mkdir /root/.ssh"
+		    umount $rootdev
+		    return 1
+		}
+	    fi
+	    # copy to both authorized_keys and _keys2
+	    cp -p /root/.ssh/authorized_keys2 $imageroot/root/.ssh/authorized_keys || {
+	        echo "Failed to create /root/.ssh/authorized_keys"
+		umount $rootdev
+		return 1
+	    }
+	    cp -p /root/.ssh/authorized_keys2 $imageroot/root/.ssh/ || {
+		echo "Failed to create /root/.ssh/authorized_keys2"
+		umount $rootdev
+		return 1
+	    }
+	fi
+    fi
+
+    # Check the host keys.
+    changehostkeys=0
+    if [ -e /etc/ssh/ssh_host_key ]; then
+	cmp -s /etc/ssh/ssh_host_key $imageroot/etc/ssh/ssh_host_key
+	if [ $? -ne 0 ]; then
+	    changehostkeys=1
+	fi
+    fi
+    if [ -e /etc/ssh/ssh_host_rsa_key ]; then
+	cmp -s /etc/ssh/ssh_host_rsa_key $imageroot/etc/ssh/ssh_host_rsa_key
+	if [ $? -ne 0 ]; then
+	    changehostkeys=1
+	fi
+    fi
+    if [ -e /etc/ssh/ssh_host_dsa_key ]; then
+	cmp -s /etc/ssh/ssh_host_dsa_key $imageroot/etc/ssh/ssh_host_dsa_key
+	if [ $? -ne 0 ]; then
+	    changehostkeys=1
+	fi
+    fi
+    if [ $changehostkeys -eq 1 ]; then
+	echo "  updating /etc/ssh/hostkeys"
+
+	if [ ! -d $imageroot/etc/ssh ]; then
+	    mkdir -m 755 $imageroot/etc/ssh || {
+		echo "Failed to mkdir $imageroot/etc/ssh"
+		umount $rootdev
+		return 1
+	    }
+	fi
+	cp -p /etc/ssh/ssh_host_* $imageroot/etc/ssh/ || {
+            echo "Failed to create /etc/ssh/hostkeys"
+	    umount $rootdev
+	    return 1
+	}
+    fi
+
+    # Check the time zone.
+    if [ -e /etc/localtime ]; then
+	cmp -s /etc/localtime $imageroot/etc/localtime
+	if [ $? -ne 0 ]; then
+	    echo "  updating /etc/localtime"
+
+	    cp -p /etc/localtime $imageroot/etc/localtime || {
+		echo "Failed to create /etc/localtime"
+		umount $rootdev
+		return 1
+	    }
+	fi
+    fi
+fi
+
 # hardwire the boss node
 if [ $setboss -eq 1 -a -d $imageroot/etc/emulab ]; then
     echo "Hardwiring boss to $bossnode"
diff --git a/clientside/tmcc/linux/slicefix b/clientside/tmcc/linux/slicefix
--- a/clientside/tmcc/linux/slicefix
+++ b/clientside/tmcc/linux/slicefix
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # EMULAB-COPYRIGHT
-# Copyright (c) 2000-2011 University of Utah and the Flux Group.
+# Copyright (c) 2000-2012 University of Utah and the Flux Group.
 # All rights reserved.
 #
 
@@ -13,8 +13,21 @@ else
 	ETCDIR=/etc/emulab
 fi
 
-freebsd_disk="ad0"
 OS=`uname -s`
+
+if [ $OS = FreeBSD ]; then
+    # XXX should fix paths.sh but I am afraid of the consequences
+    if [ -d "/etc/emulab" -a "$ETCDIR" = "/etc/testbed" ]; then
+	ETCDIR=/etc/emulab
+	for f in isvgaonly isflash bossnode emulab.pem client.pem; do
+		if [ -e "/etc/testbed/$f" -a ! -e "/etc/emulab/$f" ]; then
+			mv /etc/testbed/$f /etc/emulab/$f
+		fi
+	done
+    fi    
+fi
+
+freebsd_disk="ad0"
 
 case $# in
 1)
@@ -81,6 +94,24 @@ case $NOCLFLUSH in
     ;;
 esac
 
+VGAONLY=${SLICEFIX_VGAONLY:-'unknown'}
+case $VGAONLY in
+0|no|NO)
+    VGAONLY=no
+    ;;
+1|yes|YES)
+    VGAONLY=yes
+    ;;
+*)
+    # XXX check the MFS filesystem
+    if [ -r $ETCDIR/isvgaonly ]; then
+	VGAONLY=yes
+    else
+	VGAONLY=unknown
+    fi
+    ;;
+esac
+
 #
 # ...or the filesystem
 #
@@ -96,6 +127,17 @@ if [ -r $ETCDIR/bossnode ]; then
 else
     setboss=0
 fi
+
+# Indicates the MFS has been properly localized and we can copy stuff
+# into the image.
+LOCALIZED="/.localized"
+
+islocalized() {
+    if [ -e $LOCALIZED ]; then
+	return 0;
+    fi
+    return 1;
+}
 
 dofreebsd() {
 	#
@@ -144,8 +186,12 @@ dofreebsd() {
 		rootdev=/dev/${disk}s${part}a
 		echo "fixing FreeBSD root partition ${disk}s${part}a"
 		fsck -p $rootdev || {
-			echo "Fsck of $rootdev failed"
-			return 1
+			# 8.x fsck fails to determine the FS type, try again with ufs
+			echo "retrying fsck with '-t ufs'"
+			fsck -t ufs -p $rootdev || {
+				echo "Fsck of $rootdev failed"
+				return 1
+			}
 		}
 
 		fstype=ufs
@@ -177,6 +223,12 @@ dofreebsd() {
 	changeentropy=0
 	changeacpi=0
 	changeasf=0
+	changeclflush=0
+	changecons=0
+	changecerts=0
+	changehostkeys=0
+	changerootkeys=0
+	changezone=0
 
 	fixit=0
 
@@ -273,6 +325,21 @@ dofreebsd() {
 	    fixit=1
 	fi
 
+	#
+	# If node doesn't have a serial port, make sure comconsole is not set!
+	#
+	if [ $VGAONLY = "yes" ]; then
+	    grep "^console=\"comconsole\"" /mnt/boot/loader.conf >/dev/null 2>&1
+	    case $? in
+	    0)
+		changecons=1
+		fixit=1
+		;;
+	    *)
+	        ;;
+	    esac
+	fi
+
         # check to see if we need to download any postconfig scripts:
 	doosconfig=0
 	if [ -x $BINDIR/osconfig ]; then
@@ -280,6 +347,69 @@ dofreebsd() {
 	    if [ $? -eq 0 ]; then
 		doosconfig=1
 		fixit=1
+	    fi
+	fi
+
+	#
+	# Localize the image. We only do this if the MFS we are running in
+	# has the necessary files.
+	#
+	if islocalized; then
+	    # Check the certs.
+	    if [ -e $ETCDIR/emulab.pem ]; then
+		cmp -s $ETCDIR/emulab.pem /mnt/etc/emulab/emulab.pem
+		if [ $? -ne 0 ]; then
+		    changecerts=1
+		    fixit=1
+		fi
+	    fi
+	    if [ -e $ETCDIR/client.pem ]; then
+		cmp -s $ETCDIR/client.pem /mnt/etc/emulab/client.pem
+		if [ $? -ne 0 ]; then
+		    changecerts=1
+		    fixit=1
+		fi
+	    fi
+
+	    # Check the root keys
+	    if [ -e /root/.ssh/authorized_keys2 ]; then
+		cmp -s /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys
+		if [ $? -ne 0 ]; then
+		    changerootkeys=1
+		    fixit=1
+		fi
+	    fi
+	
+	    # Check the host keys
+	    if [ -e /etc/ssh/ssh_host_key ]; then
+		cmp -s /etc/ssh/ssh_host_key /mnt/etc/ssh/ssh_host_key
+		if [ $? -ne 0 ]; then
+		    changehostkeys=1
+		    fixit=1
+		fi
+	    fi
+	    if [ -e /etc/ssh/ssh_host_rsa_key ]; then
+		cmp -s /etc/ssh/ssh_host_rsa_key /mnt/etc/ssh/ssh_host_rsa_key
+		if [ $? -ne 0 ]; then
+		    changehostkeys=1
+		    fixit=1
+		fi
+	    fi
+	    if [ -e /etc/ssh/ssh_host_dsa_key ]; then
+		cmp -s /etc/ssh/ssh_host_dsa_key /mnt/etc/ssh/ssh_host_dsa_key
+		if [ $? -ne 0 ]; then
+		    changehostkeys=1
+		    fixit=1
+		fi
+	    fi
+
+	    # Check the time zone.
+	    if [ -e /etc/localtime ]; then
+		cmp -s /etc/localtime /mnt/etc/localtime
+		if [ $? -ne 0 ]; then
+		    changezone=1
+		    fixit=1
+		fi
 	    fi
 	fi
 
@@ -402,6 +532,22 @@ EOF2
 	fi
 
 	#
+	# Remove console="comconsole"
+	#
+	if [ $changecons -eq 1 ]; then
+	    echo "  disabling comconsole"
+	    if [ -n "$lcbak" ]; then
+		cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf${lcbak}
+		lcbak=""
+	    fi
+	    sed -E -i -e "/^console=\"comconsole\"/d" /mnt/boot/loader.conf || {
+		echo "Failed to update /boot/loader.conf"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	#
 	# See if we need to change the use of NOCLFLUSH.
 	# If explicitly specified, we override any previous setting.
 	#
@@ -425,6 +571,77 @@ EOF2
 # ${on}able CLFLUSH (hw.clflush_disable)
 hw.clflush_disable=$NOCLFLUSH
 EOF1
+	fi
+
+	# Copy in new certs
+	if [ $changecerts -eq 1 ]; then
+	    echo "  updating /etc/emulab/{emulab.pem,client.pem}"
+
+	    if [ ! -d /mnt/etc/emulab ]; then
+		mkdir -m 755 /mnt/etc/emulab || {
+	            echo "Failed to mkdir /mnt/etc/emulab"
+		    umount $rootdev
+		    return 1
+		}
+	    fi
+	    cp -p $ETCDIR/emulab.pem $ETCDIR/client.pem /mnt/etc/emulab/ || {
+	        echo "Failed to create $ETCDIR/emulab.pem or $ETCDIR/client.pem"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	# Copy in new root keys
+	if [ $changerootkeys -eq 1 ]; then
+	    echo "  updating /root/.ssh/authorized_keys"
+
+	    if [ ! -d /mnt/root/.ssh ]; then
+		mkdir -m 700 /mnt/root/.ssh || {
+	            echo "Failed to mkdir /root/.ssh"
+		    umount $rootdev
+		    return 1
+		}
+	    fi
+	    # copy to both authorized_keys and _keys2
+	    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/authorized_keys || {
+	        echo "Failed to create /root/.ssh/authorized_keys"
+		umount $rootdev
+		return 1
+	    }
+	    cp -p /root/.ssh/authorized_keys2 /mnt/root/.ssh/ || {
+	        echo "Failed to create /root/.ssh/authorized_keys2"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	# Copy in new host keys
+	if [ $changehostkeys -eq 1 ]; then
+	    echo "  updating /etc/ssh/hostkeys"
+
+	    if [ ! -d /mnt/etc/ssh ]; then
+		mkdir -m 755 /mnt/etc/ssh || {
+	            echo "Failed to mkdir /mnt/etc/ssh"
+		    umount $rootdev
+		    return 1
+		}
+	    fi
+	    cp -p /etc/ssh/ssh_host_* /mnt/etc/ssh/ || {
+	        echo "Failed to create /etc/ssh/hostkeys"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	# Copy in new localtime
+	if [ $changezone -eq 1 ]; then
+	    echo "  updating /etc/localtime"
+
+	    cp -p /etc/localtime /mnt/etc/localtime || {
+	        echo "Failed to create /etc/localtime"
+		umount $rootdev
+		return 1
+	    }
 	fi
 
 	# actually run any postconfig scripts if we're supposed to:
