Monday checkpoint checkin cpucheck - speed working but a different approch maybe be better diskcheck - working but need code for machines that do on support smartctl getfromtb.sh - add more machines redo size checks reported sizes in Mb memcheck - working but a different approch maybe be better niccheck - only counts number nics right now timecheck - works but needs to flag smaller diff value, currently 1 sec update - add more machines

diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/cpucheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/cpucheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/cpucheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/cpucheck
@@ -16,19 +16,85 @@ fi
 tmplog=/tmp/.$$.log
 cat /dev/null > ${tmplog}
 
-set +x
+#set +x
 #exit on unbound var
 #set -u
+
+#{
+case $os in
+    Linux )
+	unset -v d ; declare -a d=($(lscpu))
+	for ((idx=0; idx<${#d[*]}; idx++)) ; do
+	    [[ "${d[idx]}" == "Architecture:" ]] && break
+	done
+	    ((++idx))
+	    arch=${d[idx]}
+	echo -n "Architecture:$arch "
+	for ((idx=0; idx<${#d[*]}; idx++)) ; do
+	    [[ "${d[idx]}" == "Socket(s):" ]] && break
+	done
+	    ((++idx))
+	    sockets=${d[idx]}
+	echo -n "Sockets:$sockets "
+	for ((idx=0; idx<${#d[*]}; idx++)) ; do
+	    [[ "${d[idx]}" == "CPU(s):" ]] && break
+	done
+	    ((++idx))
+	    cores=${d[idx]}
+	echo -n "cores:$cores "
+	for ((idx=0; idx<${#d[*]}; idx++)) ; do
+	    [[ "${d[idx]}" == "MHz:" ]] && break
+	done
+	    ((++idx))
+	    mhz=${d[idx]}
+	echo "MHz:$mhz "
+	;;
+    FreeBSD )
+	    x=y=""
+	    x=$(grep 'CPU:' /var/run/dmesg.boot | grep CPU:)
+	    echo $x
+	    x=${x#CPU: }
+	    x=${x%%CPU*}
+	    x=${x%%([0-9]*}
+	    x=${x/Intel(R) /}
+	    x=${x/(R) /}
+	    arch=$x
+	    x=$(grep 'FreeBSD/SMP:' /var/run/dmesg.boot | grep package)
+	    x=${x#FreeBSD/SMP: }
+	    [[ $x ]] && sockets=${x%%package*} || sockets=1
+	    y=$(grep 'FreeBSD/SMP' /var/run/dmesg.boot | grep core)
+	    y=${y#*x }
+	    y=${y%%x*}
+	    [[ $y ]] && y=${y%%core*} || y=1
+	    cores=$(($y*$sockets))
+	    x=$(grep 'CPU\|SMP' /var/run/dmesg.boot | grep CPU:)
+	    x=${x%%-MHz*}
+	    mhz=${x##*(}
+	;;
+    * )
+	    echo "internal error cpucheck"
+	    failed=FAIL
+	    exit 1
+	    ;;
+esac
+
+#}>> ${tmplog} 2>&1
+
+# no check with tb == fail
+failed=FAIL
 
 echo "cpucheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-if [ -n ${failed} ]
+echo -n ". . . Arch:$arch Sockets:$sockets Total_Cores:$cores Mhz=$mhz "
+
+if [ -z ${failed} ]
 then
-    echo ". . . cpucheck OK"
+    echo "OK"
 else
-    echo ". . . cpucheck FAILED"
+    echo "FAILED"
 fi
+
 echo -n ""
 
 exit 0
diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
@@ -5,7 +5,8 @@
 
 # first arg is the log output file, if not set then /tmp/...
 
-source /usr/local/etc/emulab/getfromtb.sh
+#source /usr/local/etc/emulab/getfromtb.sh
+source getfromtb.sh
 
 SMARTCTL=""
 failed=""
@@ -25,63 +26,88 @@ fi
 tmplog=/tmp/.$$.log
 cat /dev/null > ${tmplog}
 
-set +x
+#set +x
 #exit on unbound var
 #set -u
 
 #need to make sure smartcrl is installed - not by default on our linux images
 {
+##     SMARTCTL=$(which smartctl)
+##     if [ -z ${SMARTCTL} ] ; then
+## 	if [ -e "/usr/sbin/smartctl" ]; then
+## 	    SMARTCTL="/usr/sbin/smartctl"
+## 	else
+## #	    [[ "$os" == "Linux" ]] && apt-get -y install smartmontools
+## 	    [[ "$os" == "FreeBSD" ]] && echo "FreeBSD: need smartcrtl installed"
+## 	fi
+##     fi
     SMARTCTL=$(which smartctl)
     if [ -z ${SMARTCTL} ] ; then
 	if [ -e "/usr/sbin/smartctl" ]; then
 	    SMARTCTL="/usr/sbin/smartctl"
-	else
-#	    [[ "$os" == "Linux" ]] && apt-get -y install smartmontools
-	    [[ "$os" == "FreeBSD" ]] && echo "FreeBSD: need smartcrtl installed"
-	fi
-    fi
-    SMARTCTL=$(which smartctl)
-    if [ -z ${SMARTCTL} ] ; then
-	if [ -e "/usr/sbin/smartctl" ]; then
-	    SMARTCTL="/usr/sbin/smartctl"
+	    good=$(($SMARTCTL --scan))
+	    if [ "${good/UNRECOGNIZED//}" == "${good}" ] ; then
+		err="no suppport --scan"
+		echo $err
+		failed="scan"
+	    fi
 	else	    
-#	    echo "smartmontools is missing and install failed"
-	    echo "smartmontools is missing "
-	    failed="FAIL"
+	    err="smartmontools missing"
+	    echo $err
+	    failed="missing"
 	fi
     fi
-    
 } >> ${tmplog} 2>&1
-if [ $failed ] ; then
-    echo "diskcheck `date`" >> ${logfile}
-    cat ${tmplog} >> ${logfile} 
-    echo ". . . diskcheck FAILED"
-    exit 1
-fi
 
-# needed ?
+echo "diskcheck `date`" >> ${logfile}
+cat ${tmplog} >> ${logfile} 
+
+[[ $failed ]] && echo -n ". . . $err attempt workaround " || echo -n ". . . "
+
 
 # index into dirveinv array
 name=0; driver=1; type=2; size=3; temp=4; model=5;
+unset -v driveinv ; declare -a driveinv=()
 
 # put smartctl --scan into drive array
-unset -v scan ; declare -a scan=($($SMARTCTL --scan))
-unset -v drive ; declare -a drivescan=()
-y=0
-for elm in ${scan[@]} ; do
-    drivescan[$y]="${drivescan[$y]} ${elm}"
-    [[ "${elm}" == "device" ]] && ((++y))
-done
+# bad control flow control - need to replace
+case $failed in
+    scan )
+	driveinv[$name]="NoScan"
+	driveinv[$driver]="UKN"
+	driveinv[$type]="UKN"
+	driveinv[$size]="0GB"
+	driveinv[$temp]="UKN"
+	driveinv[$model]="UKN"
+	;;
+    missing )
+	driveinv[$name]="Missing"
+	driveinv[$driver]="UKN"
+	driveinv[$type]="UKN"
+	driveinv[$size]="0GB"
+	driveinv[$temp]="UKN"
+	driveinv[$model]="UKN"
+	;;
+    * )
+    unset -v scan ; declare -a scan=($($SMARTCTL --scan))
+    unset -v drive ; declare -a drivescan=()
+    y=0
+    for elm in ${scan[@]} ; do
+	drivescan[$y]="${drivescan[$y]} ${elm}"
+	[[ "${elm}" == "device" ]] && ((++y))
+    done
 
 # collect info into driveinv array
-unset -v driveinv ; declare -a driveinv=()
 for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
     unset -v d ; declare -a d=(${drivescan[$idx]})
     lend=${#d[*]} ; x=$((lend - 2))
 
     #name
     cnt=${#driveinv[$idx]}
-    driveinv[$idx]="${d[0]}"
+    lname="${d[0]}"
+    sname="${lname:5}"
+    [[  "$sname" == "pass2" ]] && break # /dev/pass2 on freebsd tape device
+    driveinv[$idx]="$sname"
     [[ ${#driveinv[*]} -eq $cnt ]] && driveinv[$idx]="NA"
     driveinv[$idx]+=" "
 
@@ -125,6 +151,8 @@ for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
     [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
     driveinv[$idx]+=" "
 done
+;;
+esac
 
 ## # does number of drives and size match ?
 ## # getfromtb operation node_id drivename drive size
@@ -135,7 +163,7 @@ done
 
 #output to log file - then quit
 {
-echo -e "name\t\tdriver\t\ttype\tsize\ttemp\tmodel"
+echo -e "name\tdriver\t\ttype\tsize\ttemp\tmodel"
 for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
     unset -v d ; declare -a d=(${driveinv[$idx]})
     echo -e "${d[$name]}\t${d[$driver]}\t\t${d[$type]}\t${d[$size]}\t${d[$temp]}\t${d[$model]}"
@@ -145,12 +173,31 @@ done
 echo "diskcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-if [ -n ${failed} ]
-then
-    echo ". . . diskcheck OK"
+drivestring=drivesize=""
+
+if [ -z $failed ] ; then
+    for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
+	unset -v d ; declare -a d=(${driveinv[$idx]})
+	echo -n "${d[$name]} ${d[$size]} "
+	drivestring+="${d[$name]} ${d[$size]} "
+	drivesize+="${d[$size]} "
+    done
+    drivesize=${drivesize% } # get rid of trailing space
 else
-    echo ". . . diskcheck FAILED"
+	echo -n "id:${driveinv[$name]} size:${driveinv[$size]} model:${driveinv[$model]}"
+	failed="FATEL"
 fi
+
+# Now check against the testbed DB
+
+tbinfo=$(getfromtb diskinfo $host)
+err=$?
+# echo drivesize:$drivesize: tbinfo:$tbinfo: err:$err
+
+[[ "$tbinfo" == "$drivesize" ]] && failed="" || failed="MISSMATCHED $tbinfo"
+
+
+[[ ${failed} ]] && echo " ${failed}" || echo " OK"
 echo -n ""
 
 exit 0
diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
@@ -1,14 +1,8 @@
 #! /bin/bash
 
-source /usr/local/etc/emulab/getfromtb.sh
+#source /usr/local/etc/emulab/getfromtb.sh
 #source /home/dreading/r710diskstudies/usr/local/etc/emulab/getfromtb.sh
-
-# smallest chunk to count with, in MiB
-SmallestCNT=256
-KiB=1024
-KiB256=$(($KiB*${SmallestCNT}))  #smallest chunk to count with
-MiB=1048576
-GiB=1073741824
+source getfromtb.sh
 
 os=`uname`
 host=`hostname`
@@ -29,75 +23,7 @@ cat /dev/null > ${tmplog}
 
 set +x
 #exit on unbound var
-#set -u
-
-#how big is this
-hbis() {
-    number=$1
-#number="250260kB"
-#number="443124kB"
-#number="4000848kB"
-#number="8110204kB"
-    base=""
-
-    # what units is the number in
-    x=$number
-    y=$(echo ${x,,}) #lower case letters
-
-    if [ ${y%%m*} != ${y} ] ; then
-	# its in megs
-	base="m"
-	# strip letters
-	number=${y%%m*}
-	bytes=$((${number}*$MiB))
-    elif [ ${y%%g*} != ${y} ] ; then
-	base="g"
-	number=${y%%g*}
-	bytes=$((${number}*$GiB))
-    elif [ ${y%%k*} != ${y} ] ; then
-	number=${y%%k*}
-	base="k"
-	bytes=$((${number}*$KiB))
-    else
-	base="b"
-	number=${y%%[a-z]*}
-	bytes=$number
-    fi
-
-    # return numbers in MiB
-    case $base in
-	g )
-	    c=0
-	    for ((x=$GiB;;x+=$GiB)) ; do
-		((++c))
-		[[ $x -ge $bytes ]] && break
-	    done
-	    echo ${c}GiB
-	    ;;
-	m )
-	    c=0
-	    for ((x=$MiB;;x+=$MiB)) ; do
-		((++c))
-		[[ $x -ge $bytes ]] && break
-	    done
-	    echo ${c}MiB
-	    ;;
-
-	k )
-	    c=0
-	    for ((x=${KiB256};;x+=${KiB256})) ; do
-		((++c))
-		[[ $x -ge $number ]] && break
-	    done
-	    [[ $number -ge $(($MiB*4)) ]] && ((++c))
-	    echo $((${c}*${SmallestCNT}))MiB
-	    ;;
-	
-	b )
-	    echo ${number}BiB
-	    ;;
-    esac
-}
+set -u
 
 {
 case $os in
@@ -125,12 +51,10 @@ echo -n "Found phys memory $meminfo"
 } >> ${tmplog} 2>&1
 
 tbinfo=$(getfromtb meminfo $host)
-a=${tbinfo,,} ; b=${meminfo,,}
-x=${a%%g*} y=${b%%g*}
-echo meminfo:$meminfo x=$x tbinfo:$tbinfo y=$y
+# echo meminfo:$meminfo tbinfo:$tbinfo
 
 {
-if [ "$x" == "$y" ] ; then
+if [ "$meminfo" == "$tbinfo" ] ; then
     echo " equals node inventory $tbinfo"
 else
     echo " does not equals node inventory $tbinfo"    
@@ -141,6 +65,6 @@ fi
 echo "memcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo ". . . $tbinfo memcheck OK" || echo ". . . memcheck $meminfo FAILED"
+[[ -z ${failed} ]] && echo ". . . $tbinfo OK" || echo ". . . $meminfo is not $tbinfo FAILED"
 
 exit 0
