rename all files and needed contents to change the text from test -> check

diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskspeedcheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskspeedcheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskspeedcheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskspeedcheck
@@ -28,13 +28,13 @@ set -u
 logfile=$1
 
 {
-
+echo ""
 } >> ${tmplog} 2>&1
 
-echo "diskspeedtest `date`" >> ${logfile}
+echo "diskspeedcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo ". . . diskspeedtest OK" || echo ". . . diskspeedtest FAILED"
+[[ -z ${failed} ]] && echo ". . . diskspeedcheck OK" || echo ". . . diskspeedcheck FAILED"
 
 exit 0
 
diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/memcheck
@@ -55,9 +55,9 @@ else
 fi
 } >> ${tmplog} 2>&1
 
-echo "memtest `date`" >> ${logfile}
+echo "memcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo ". . . memtest OK" || echo ". . . memtest FAILED"
+[[ -z ${failed} ]] && echo ". . . memcheck OK" || echo ". . . memcheck FAILED"
 
 exit 0
diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/niccheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/niccheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/niccheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/niccheck
@@ -46,18 +46,18 @@ esac
 
 #tbinfo=$(getfromtb meminfo $host)
 
-{
-if [ "$tbinfo" == "$meminfo" ] ; then
+#{
+#if [ "$tbinfo" == "$meminfo" ] ; then
  #   echo " equals node inventory $tbinfo"
-else
+#else
 #    echo " does not equals node inventory $tbinfo"    
 #    failed=FAIL
-fi
-} >> ${tmplog} 2>&1
+#fi
+#} >> ${tmplog} 2>&1
 
-echo "memtest `date`" >> ${logfile}
+echo "niccheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo ". . . SKEL OK" || echo ". . . SKEL FAILED"
+[[ -z ${failed} ]] && echo ". . . niccheck OK" || echo ". . . nictest FAILED"
 
 exit 0
