A checkpoint just in case: mostly working but need to handle alt ways to get disk info

diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/diskcheck
@@ -30,7 +30,7 @@ cat /dev/null > ${tmplog}
 
 #set +x
 #exit on unbound var
-#set -u
+set -u
 
 #need to make sure smartcrl is installed - not by default on our linux images
 {
@@ -38,32 +38,34 @@ cat /dev/null > ${tmplog}
     if [ -z ${SMARTCTL} ] ; then
 	if [ -e "/usr/sbin/smartctl" ]; then
 	    SMARTCTL="/usr/sbin/smartctl"
-	    good=$(($SMARTCTL --scan))
-	    if [ "${good/UNRECOGNIZED//}" == "${good}" ] ; then
-		err="no suppport --scan"
-		echo $err
-		failed="scan"
-	    fi
-	else	    
-	    err="smartmontools missing"
-	    echo $err
-	    failed="missing"
 	fi
+    fi
+    if [ ${SMARTCTL} ] ; then
+	good=$($SMARTCTL --scan)
+	if [ -z ${good} -o \( "${good/UNRECOGNIZED//}" == "${good}" \)  ] ; then
+	    err="smartctl --scan not supported"
+	    echo $err
+	    failed="scan"
+	fi
+    else	    
+	err="smartmontools missing"
+	echo $err
+	failed="missing"
     fi
 } >> ${tmplog} 2>&1
 
 echo "diskcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ $failed ]] && echo -n "$err attempt workaround " || echo -n " "
+[[ $failed ]] && echo "$err attempt workaround " || echo -n " "
 
 
-# index into dirveinv array
-name=0; driver=1; type=2; size=3; temp=4; model=5;
+# the index into dirveinv array
+name=0; driver=1; type=2; size=3; temp=4; model=5; serial=6;
 unset -v driveinv ; declare -a driveinv=()
 
-# put smartctl --scan into drive array
-# bad control flow control - need to replace
+# put smartctl --scan into driveinv array
+# a better control flow control could be used 
 case $failed in
     scan )
 	driveinv[$name]="NoScan"
@@ -82,15 +84,21 @@ case $failed in
 	driveinv[$model]="UKN"
 	;;
     * )
+
+    # get the output of --scan into array scan
     unset -v scan ; declare -a scan=($($SMARTCTL --scan))
     unset -v drive ; declare -a drivescan=()
+    #now split up each line using 'device' into the array drivescan
+    # This is an example of the string we are parsing:
+    # '/dev/sdb -d scsi # /dev/sdb, SCSI device'    
     y=0
-    for elm in ${scan[@]} ; do
+     for elm in ${scan[@]} ; do
+set +u
 	drivescan[$y]="${drivescan[$y]} ${elm}"
 	[[ "${elm}" == "device" ]] && ((++y))
+set -u
     done
 
-# collect info into driveinv array
 for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
     unset -v d ; declare -a d=(${drivescan[$idx]})
     lend=${#d[*]} ; x=$((lend - 2))
@@ -99,27 +107,28 @@ for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
     cnt=${#driveinv[$idx]}
     lname="${d[0]}"
     sname="${lname:5}"
-    [[  "$sname" == "pass2" ]] && break # /dev/pass2 on freebsd tape device
+    [[  "$sname" == "pass2" ]] && break # /dev/pass2 on freebsd is tape device, skip
     driveinv[$idx]="$sname"
-    [[ ${#driveinv[*]} -eq $cnt ]] && driveinv[$idx]="NA"
+    #if we did not get any info then fill in value meaning unknown.
+    [[ ${#driveinv[*]} -eq $cnt ]] && driveinv[$idx]="MissingCMD"
     driveinv[$idx]+=" "
 
     #driver
     cnt=${#driveinv[$idx]}
     driveinv[$idx]+="${d[2]}"
-    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
     driveinv[$idx]+=" "
 
     #type
     cnt=${#driveinv[$idx]}
     driveinv[$idx]+="${d[$x]}"
-    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
     driveinv[$idx]+=" "
 
     #size
     cnt=${#driveinv[$idx]}
     driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "capacity" | awk '{print $5$6}' | sed s/[][]//g)"
-    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
     driveinv[$idx]+=" "
 
     #temp
@@ -130,7 +139,7 @@ for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
         #type 2
 	driveinv[$idx]+="$($SMARTCTL  -a ${d[0]} | grep "Current Drive Temperature:" | awk '{print $4}')"
     fi
-    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
     driveinv[$idx]+=" "
 
     #vendor product
@@ -141,7 +150,12 @@ for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
         #type 2
 	driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Product:" | awk '{print $2}')"
     fi
-    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="NA"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
+    driveinv[$idx]+=" "
+
+    # serial number
+    driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep "Serial Number:" | awk '{print $3}')"
+    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
     driveinv[$idx]+=" "
 done
 ;;
@@ -154,30 +168,29 @@ esac
 ##     tbdata=getfromtb $host driveinfo ${d[$name]} 
 ## done
 
-#output to log file - then quit
+#output to log file
 {
-echo -e "name\tdriver\t\ttype\tsize\ttemp\tmodel"
+echo -e "name\tdriver\ttype\tsize\ttemp\tmodel\tserial"
 for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
     unset -v d ; declare -a d=(${driveinv[$idx]})
-    echo -e "${d[$name]}\t${d[$driver]}\t\t${d[$type]}\t${d[$size]}\t${d[$temp]}\t${d[$model]}"
+    echo -e "${d[$name]}\t${d[$driver]}\t${d[$type]}\t${d[$size]}\t${d[$temp]}\t${d[$model]}\t${d[$serial]}"
 done
 } >> ${tmplog} 2>&1
 
 echo "diskcheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-drivestring=drivesize=""
+driveinfo=""
 
 if [ -z $failed ] ; then
     for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
 	unset -v d ; declare -a d=(${driveinv[$idx]})
-	echo -n "${d[$name]} ${d[$size]} "
-	drivestring+="${d[$name]} ${d[$size]} "
-	drivesize+="${d[$size]} "
+	echo -n "${d[$name]} ${d[$size]} ${d[$serial]}"
+	driveinfo+="${d[$serial]} "
     done
-    drivesize=${drivesize% } # get rid of trailing space
+    driveinfo=${driveinfo% } # get rid of trailing space
 else
-	echo -n "id:${driveinv[$name]} size:${driveinv[$size]} model:${driveinv[$model]}"
+	echo -n "id:${driveinv[$name]} size:${driveinv[$size]} model:${driveinv[$model]} serial:${driveinv[$serial]}"
 	failed="FATEL"
 fi
 
@@ -187,10 +200,10 @@ tbinfo=$(getfromtb diskinfo $host)
 err=$?
 # echo drivesize:$drivesize: tbinfo:$tbinfo: err:$err
 
-[[ "$tbinfo" == "$drivesize" ]] && failed="" || failed="TBmissed Have |$drivesize| Want |$tbinfo|"
+[[ "$tbinfo" == "$driveinfo" ]] && failed="" || failed="TBmiss Have |$driveinfo| Want |$tbinfo|"
 
 
-[[ ${failed} ]] && echo " ${failed}" || echo " OK"
+[[ ${failed} ]] && echo " ${failed} FAILED" || echo " OK"
 echo -n ""
 
 exit 0
