fix logic bug add handling of non-resposive ntpserver

diff --git a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/timecheck b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/timecheck
--- a/clientside/tmcc/common/nodetest/usr/local/etc/emulab/timecheck
+++ b/clientside/tmcc/common/nodetest/usr/local/etc/emulab/timecheck
@@ -1,6 +1,8 @@
 #! /bin/sh
 
 ntpserver="155.98.32.70"
+maxdrift="0.05"
+
 #ntpserver="time.xmission.com"
 
 os=`uname`
@@ -20,28 +22,36 @@ fi
 tmplog=/tmp/.$$.log
 cat /dev/null > ${tmplog}
 
-#set +x
 #exit on unbound var
-#set -u
+set -u
 
 {
+unset -v d ; declare -a d=()
 case $os in
     Linux | FreeBSD )
-	unset -v d ; declare -a d=($(ntpdate -q $ntpserver))
+	d=($(ntpdate -q $ntpserver))
+	(( $? )) && failed="No Response from ntpserver:$ntpserver"
+
 	for ((idx=0; idx<${#d[*]}; idx++)) ; do
-	    [[ "${d[idx]}" == "offset" ]] && break
+	    [[ "${d[$idx]}" == "offset" ]] && break
 	done
 	((++idx))
-	z=${d[idx]}
-	offset=$(echo ${z} | tr -d ,)
-	[[ $offset < 0 ]] && a=$(echo "-(10 * $offset)" | bc) || a=$(echo "(10 * $offset)" | bc)
-	[[ $a > 1 ]] && failed=FAIL
-	[[ $failed ]] && echo "Time check failed offset $offset greater then 1 second " || echo "Time check passed offset $offset"
+	z=${d[$idx]}
+	offset=$(echo ${z} | tr -d ,) # remove comma
+	[[ $offset < -1 ]] && a=$(echo "-($offset)" | bc) || a=$(echo "($offset)" | bc) # make $a abs()
+	[[ $a > $maxdrift ]] && failed="maxdrift"
+	if  [ -z "${failed}" ]; then
+	    echo "Time check passed offset $offset alowed $maxdrift"
+	elif [ "${failed}" == "maxdrift" ] ; then
+	    echo "Time check failed offset $offset greater then $maxdrift second "
+	else
+	    echo "${failed}"
+	fi
 	;;
     * )
 	echo "os $os unknown"
 	offset="-1"
-	failed=FAIL
+	failed="os $os unknown"
 	;;
 esac
 } >> ${tmplog} 2>&1
@@ -49,6 +59,12 @@ esac
 echo "timecheck `date`" >> ${logfile}
 cat ${tmplog} >> ${logfile} 
 
-[[ -z ${failed} ]] && echo ". . . offset $offset OK" || echo ". . . offset $offset FAILED"
+if [ -z "${failed}" ] ; then 
+    echo ". . . offset |$offset| < $maxdrift OK" 
+elif [ "${failed}" == "maxdrift" ] ; then
+    echo ". . . offset |$offset| > $maxdrift FAILED"
+else
+    echo ". . . ${failed} FAILED"
+fi
 
 exit 0
